release-date = "2022-07-09"

[[entries]]
id = "e62dfe82-9869-4e1b-a9b3-08c6ff010159"
type = "feature"
description = "Adds ability to use alternative nameservers; fixes ETA to show timezone; adds list index information to logs"
author = "ndejong@threatpatrols.com"
