
name: domain-email-records
version: 0.4.2
license: BSD2
author: Nicholas de Jong <ndejong@threatpatrols.com>

description: "CLI tool to quickly lookup MX, SPF, DMARC records for many domains"
url: https://github.com/ndejong/domain-email-records

typed: false

entrypoints:
  console_scripts:
    - domain-email-records = domain_email_records.cli_entrypoint:main

requirements:
  - python ^3.7
  - dnspython
  - async_lru

test-drivers:
  - type: pylint
    args: [ '--fail-under=8.0', '--indent-string="    "' ]

templates:
  - type: pylintrc
    use: shut

keywords:
  - "domain-name"
  - "dns"
  - "email"
  - "spf"
  - "dmarc"

classifiers:
  - "Environment :: Console"
  - "Intended Audience :: System Administrators"
  - "Intended Audience :: Information Technology"
  - "Programming Language :: Python :: 3"
  - "License :: OSI Approved :: BSD License"

publish:
  pypi:
    enabled: true
